# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Apx < Formula
  desc "CLI wrapper for platform-specific sandboxes"
  homepage "https://github.com/UsingCoding/apx"
  version "0.0.8"
  license "MIT"

  depends_on "go" => :build

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/UsingCoding/apx/releases/download/v0.0.8/apx_0.0.8_darwin_x86_64.tar.gz"
      sha256 "78ad10f09c5cfc754a898bccfdfaf13fa3651764e6e2e707899c7c60c06c7525"

      def install
        ldflags = %W[
          -s -w
          -X main.version=#{version}
          -X main.commit=homebrew
        ]
        system "go", "build", *std_go_args(ldflags: ldflags, output: bin/"apx"), "./cmd/apx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/UsingCoding/apx/releases/download/v0.0.8/apx_0.0.8_darwin_arm64.tar.gz"
      sha256 "22a50a372c7e5b2c971768b3575f425de2da9c3092732363f11ad3a2023e0867"

      def install
        ldflags = %W[
          -s -w
          -X main.version=#{version}
          -X main.commit=homebrew
        ]
        system "go", "build", *std_go_args(ldflags: ldflags, output: bin/"apx"), "./cmd/apx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/UsingCoding/apx/releases/download/v0.0.8/apx_0.0.8_linux_x86_64.tar.gz"
      sha256 "bd7b6b86fd52b051c3c9686e07b962bd847652d29f04b025354c4ecc0afc6e3e"
      def install
        ldflags = %W[
          -s -w
          -X main.version=#{version}
          -X main.commit=homebrew
        ]
        system "go", "build", *std_go_args(ldflags: ldflags, output: bin/"apx"), "./cmd/apx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/UsingCoding/apx/releases/download/v0.0.8/apx_0.0.8_linux_arm64.tar.gz"
      sha256 "1570dc7e84880574ffb65a9ed252002180a50a5f195371f46c0f1ec71b79850a"
      def install
        ldflags = %W[
          -s -w
          -X main.version=#{version}
          -X main.commit=homebrew
        ]
        system "go", "build", *std_go_args(ldflags: ldflags, output: bin/"apx"), "./cmd/apx"
      end
    end
  end
end
