# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Apx < Formula
  desc "CLI wrapper for platform-specific sandboxes"
  homepage "https://github.com/UsingCoding/apx"
  version "0.0.12"
  license "MIT"

  depends_on "go" => :build

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/UsingCoding/apx/releases/download/v0.0.12/apx_0.0.12_darwin_x86_64.tar.gz"
      sha256 "2930bbdb6ac9b48a845b6533e6ce6c1732c67245832eb6218383c70451c86dbe"

      def install
        ldflags = %W[
          -s -w
          -X main.version=#{version}
          -X main.commit=homebrew
        ]
        system "go", "build", *std_go_args(ldflags: ldflags, output: bin/"apx"), "./cmd/apx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/UsingCoding/apx/releases/download/v0.0.12/apx_0.0.12_darwin_arm64.tar.gz"
      sha256 "f2dbf1dbbc1b31fc077e3c9a34bbffbd069cff78213b2bb647b5c8dce39e31a3"

      def install
        ldflags = %W[
          -s -w
          -X main.version=#{version}
          -X main.commit=homebrew
        ]
        system "go", "build", *std_go_args(ldflags: ldflags, output: bin/"apx"), "./cmd/apx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/UsingCoding/apx/releases/download/v0.0.12/apx_0.0.12_linux_x86_64.tar.gz"
      sha256 "605d4a0c5e7a8346cb94fc793bea176b3f9ef68bbca920740cb5a18bf3185f56"
      def install
        ldflags = %W[
          -s -w
          -X main.version=#{version}
          -X main.commit=homebrew
        ]
        system "go", "build", *std_go_args(ldflags: ldflags, output: bin/"apx"), "./cmd/apx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/UsingCoding/apx/releases/download/v0.0.12/apx_0.0.12_linux_arm64.tar.gz"
      sha256 "a4ed635653331bfe125bd7051a58a84049b22a5cd1165449146c8207bad0e60e"
      def install
        ldflags = %W[
          -s -w
          -X main.version=#{version}
          -X main.commit=homebrew
        ]
        system "go", "build", *std_go_args(ldflags: ldflags, output: bin/"apx"), "./cmd/apx"
      end
    end
  end
end
