# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Apx < Formula
  desc "CLI wrapper for platform-specific sandboxes"
  homepage "https://github.com/UsingCoding/apx"
  version "0.0.11"
  license "MIT"

  depends_on "go" => :build

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/UsingCoding/apx/releases/download/v0.0.11/apx_0.0.11_darwin_x86_64.tar.gz"
      sha256 "f07d6d98ffdf16da528fd77b7276896bf2865358c9f66ff5870b1003f836f0a9"

      def install
        ldflags = %W[
          -s -w
          -X main.version=#{version}
          -X main.commit=homebrew
        ]
        system "go", "build", *std_go_args(ldflags: ldflags, output: bin/"apx"), "./cmd/apx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/UsingCoding/apx/releases/download/v0.0.11/apx_0.0.11_darwin_arm64.tar.gz"
      sha256 "59d77402b8943d07414ad189a4de24d39bfe5859e41e400a5f33e6092290943f"

      def install
        ldflags = %W[
          -s -w
          -X main.version=#{version}
          -X main.commit=homebrew
        ]
        system "go", "build", *std_go_args(ldflags: ldflags, output: bin/"apx"), "./cmd/apx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/UsingCoding/apx/releases/download/v0.0.11/apx_0.0.11_linux_x86_64.tar.gz"
      sha256 "50f06649b79e397af80e1f3c273105c774a0c07cb3102d0103fd530b6622a038"
      def install
        ldflags = %W[
          -s -w
          -X main.version=#{version}
          -X main.commit=homebrew
        ]
        system "go", "build", *std_go_args(ldflags: ldflags, output: bin/"apx"), "./cmd/apx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/UsingCoding/apx/releases/download/v0.0.11/apx_0.0.11_linux_arm64.tar.gz"
      sha256 "6ba103b8563ba212347523e95fda7254bfc32d153ae0688e8629087865abf496"
      def install
        ldflags = %W[
          -s -w
          -X main.version=#{version}
          -X main.commit=homebrew
        ]
        system "go", "build", *std_go_args(ldflags: ldflags, output: bin/"apx"), "./cmd/apx"
      end
    end
  end
end
