# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gostore < Formula
  desc "Secret store manager"
  homepage "https://github.com/UsingCoding/gostore"
  version "1.7.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/UsingCoding/gostore/releases/download/v1.7.0/gostore_1.7.0_darwin_x86_64.tar.gz"
      sha256 "298b15a6ad43941e025695819e17f8938fd96b098adbeab2ff3639016bb1cc52"

      def install
        bin.install "gostore"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/UsingCoding/gostore/releases/download/v1.7.0/gostore_1.7.0_darwin_arm64.tar.gz"
      sha256 "6f7b901a98d65614e011348c63723ef494c882752fbd2336daed3e3f8ec81274"

      def install
        bin.install "gostore"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/UsingCoding/gostore/releases/download/v1.7.0/gostore_1.7.0_linux_x86_64.tar.gz"
      sha256 "2762922b3cf20375fd211c54b69be41e2c9dc45227642b3548d67f3b72e11f12"
      def install
        bin.install "gostore"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/UsingCoding/gostore/releases/download/v1.7.0/gostore_1.7.0_linux_arm64.tar.gz"
      sha256 "2517590ffa220c3da02cf7b76bbb99dbc56341eb3d30a2ed37c7fe960b891bd8"
      def install
        bin.install "gostore"
      end
    end
  end
end
