# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gostore < Formula
  desc "Secret store manager"
  homepage "https://github.com/UsingCoding/gostore"
  version "1.5.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/UsingCoding/gostore/releases/download/v1.5.1/gostore_1.5.1_darwin_x86_64.tar.gz"
      sha256 "0149752b4bcc7aae78cf0f7d5e87a1abcf8f3b1ef5531f1dac0a5234e78dc6c0"

      def install
        bin.install "gostore"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/UsingCoding/gostore/releases/download/v1.5.1/gostore_1.5.1_darwin_arm64.tar.gz"
      sha256 "895fbb8aea0a09e8cbd4bf3f11971ae36cab56a6f939d962084e1758750cca41"

      def install
        bin.install "gostore"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/UsingCoding/gostore/releases/download/v1.5.1/gostore_1.5.1_linux_x86_64.tar.gz"
      sha256 "5e40ea54b435b4607e5afca607d047908e4ad9d981e8a411cb659a015e70285f"
      def install
        bin.install "gostore"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/UsingCoding/gostore/releases/download/v1.5.1/gostore_1.5.1_linux_arm64.tar.gz"
      sha256 "ead3f6b92b71d0583e115149ebd04e80ad97022caea1a6948c93c433aa1eef1b"
      def install
        bin.install "gostore"
      end
    end
  end
end
