# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GostoreAgent < Formula
  desc "Agent to expose ssh keys stored in gostore over ssh-agent"
  homepage "https://github.com/UsingCoding/gostore"
  version "0.0.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/UsingCoding/gostore-agent/releases/download/v0.0.4/gostore-agent_0.0.4_darwin_x86_64.tar.gz"
      sha256 "e2b065162233e88cba631621964206fa2fb11f3f8ff367c22aad023be3619489"

      def install
        bin.install "gostore-agent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/UsingCoding/gostore-agent/releases/download/v0.0.4/gostore-agent_0.0.4_darwin_arm64.tar.gz"
      sha256 "62ff44049d8b7484a13fd532003aa85cd0ce618fea0d0008cce3083a0b350dc2"

      def install
        bin.install "gostore-agent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/UsingCoding/gostore-agent/releases/download/v0.0.4/gostore-agent_0.0.4_linux_x86_64.tar.gz"
        sha256 "fd81de8255ca9e7a94a08e5f4dea3bc0f3011dfab6848b938d617a60aecc4995"

        def install
          bin.install "gostore-agent"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/UsingCoding/gostore-agent/releases/download/v0.0.4/gostore-agent_0.0.4_linux_arm64.tar.gz"
        sha256 "157cee7980061907c3df66c8e9d75beadbfd774bbde6bbdcc42aeadba0e6c83a"

        def install
          bin.install "gostore-agent"
        end
      end
    end
  end

  def post_install
    (var/"run").mkpath
    system "#{bin}/gostore-agent", "install"
  end

  service do
    run [opt_bin/"gostore-agent", "-s", var/"run/gostore-agent.sock"]
    keep_alive true
    log_path var/"log/gostore-agent.log"
    error_log_path var/"log/gostore-agent.log"
  end
end
