# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gostore < Formula
  desc "Secret store manager"
  homepage "https://github.com/UsingCoding/gostore"
  version "1.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/UsingCoding/gostore/releases/download/v1.3.0/gostore_1.3.0_darwin_x86_64.tar.gz"
      sha256 "be1648eb7b42577f0ac757713f593dc649748ca9a17c3548b44ec521a6335a49"

      def install
        bin.install "gostore"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/UsingCoding/gostore/releases/download/v1.3.0/gostore_1.3.0_darwin_arm64.tar.gz"
      sha256 "af2c232ed67ef9daff24162e7dc76f3ca9208b342f12253fa00fd1457dd015ed"

      def install
        bin.install "gostore"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/UsingCoding/gostore/releases/download/v1.3.0/gostore_1.3.0_linux_x86_64.tar.gz"
        sha256 "ab91d2746250dfab506af10353ac4dd6ea600cda475d0f040e2aea81bf576579"

        def install
          bin.install "gostore"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/UsingCoding/gostore/releases/download/v1.3.0/gostore_1.3.0_linux_arm64.tar.gz"
        sha256 "3aa283a66d817a5323e77a43503a8c31bce0e4fc9de89dc1032d0ba003ad8159"

        def install
          bin.install "gostore"
        end
      end
    end
  end
end
