# This file was generated by GoReleaser. DO NOT EDIT.
cask "apx" do
  name "apx"
  desc "CLI wrapper for platform-specific sandboxes"
  homepage "https://github.com/UsingCoding/apx"
  version "0.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "apx"

  on_macos do
    on_intel do
      url "https://github.com/UsingCoding/apx/releases/download/v#{version}/apx_#{version}_darwin_x86_64.tar.gz"
      sha256 "0c4f93148a2d057b0562ba074d5874c0e2510fb941c4ec1ba717d2456d7a1b42"
    end
    on_arm do
      url "https://github.com/UsingCoding/apx/releases/download/v#{version}/apx_#{version}_darwin_arm64.tar.gz"
      sha256 "76ac1b6901cbd286d5748f32c306a56e526992b7d592750d3b37126a32de6648"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/UsingCoding/apx/releases/download/v#{version}/apx_#{version}_linux_x86_64.tar.gz"
      sha256 "270e167d0e00a9ae9b69d9efc68283b30deea88851e5b3f72221a7a45ac8b505"
    end
    on_arm do
      url "https://github.com/UsingCoding/apx/releases/download/v#{version}/apx_#{version}_linux_arm64.tar.gz"
      sha256 "0d58767ddbe99c214f9685b0928454e9f63ccf2ab0c85ab321be496b04938a2a"
    end
  end

  caveats do
    "To activate apx helpers execute:"
    "  - bash: echo 'eval "$(apx shellenv bash)"' >> ~/.bashrc"
    "  - zsh:  echo 'eval "$(apx shellenv zsh)"' >> ~/.zshrc"
  end

  # No zap stanza required
end
