# This file was generated by GoReleaser. DO NOT EDIT.
cask "apx" do
  name "apx"
  desc "CLI wrapper for platform-specific sandboxes"
  homepage "https://github.com/UsingCoding/apx"
  version "0.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "apx"

  on_macos do
    on_intel do
      url "https://github.com/UsingCoding/apx/releases/download/v#{version}/apx_#{version}_darwin_x86_64.tar.gz"
      sha256 "d4d4c4a9099e8b7ec08c65b2ee2c86b27f54f98ef3c2f6284ad8c8b55e99db61"
    end
    on_arm do
      url "https://github.com/UsingCoding/apx/releases/download/v#{version}/apx_#{version}_darwin_arm64.tar.gz"
      sha256 "d5960d909d5501ade994ae386d4691c62439b012c221746dddd5d56fc7b3b2d2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/UsingCoding/apx/releases/download/v#{version}/apx_#{version}_linux_x86_64.tar.gz"
      sha256 "140a63f2ad25d15df05fe12a317d2ab5c34951dabab8e517039e4a4029239bc4"
    end
    on_arm do
      url "https://github.com/UsingCoding/apx/releases/download/v#{version}/apx_#{version}_linux_arm64.tar.gz"
      sha256 "33a3dae6ade1c8176f726e9766d93fef2629203cf52ead3887d56f23c4ec3f40"
    end
  end

  # No zap stanza required
end
